#Minecraft server properties
#Thu Nov 21 19:15:54 JST 2019
spawn-protection=1
max-tick-time=60000
query.port=25565
server-name=n_server
generator-settings=
force-gamemode=false
allow-nether=false
enforce-whitelist=false
gamemode=REPLACE_MODE
broadcast-console-to-ops=true
enable-query=false
player-idle-timeout=0
difficulty=REPLACE_DIFFICULTY
spawn-monsters=REPLACE_SPAWN
broadcast-rcon-to-ops=true
op-permission-level=4
pvp=false
snooper-enabled=false
level-type=
hardcore=false
enable-command-block=true
max-players=150
network-compression-threshold=256
resource-pack-sha1=
max-world-size=10000
function-permission-level=2
rcon.port=25575
server-port=25565
debug=false
server-ip=
spawn-npcs=REPLACE_SPAWN
allow-flight=false
level-name=njhs
view-distance=8
resource-pack=
spawn-animals=REPLACE_SPAWN
white-list=false
rcon.password=REPLACE_RCON
generate-structures=REPLACE_SPAWN
online-mode=false
max-build-height=256
level-seed=7401161022981800019
prevent-proxy-connections=false
use-native-transport=true
motd=n_server
enable-rcon=true
